// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protoc/excel.proto

package protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type SendExcelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Filename      *string                `protobuf:"bytes,4,opt,name=filename,proto3,oneof" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,5,opt,name=content,proto3,oneof" json:"content,omitempty"`
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3,oneof" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendExcelRequest) Reset() {
	*x = SendExcelRequest{}
	mi := &file_protoc_excel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendExcelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendExcelRequest) ProtoMessage() {}

func (x *SendExcelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_excel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendExcelRequest.ProtoReflect.Descriptor instead.
func (*SendExcelRequest) Descriptor() ([]byte, []int) {
	return file_protoc_excel_proto_rawDescGZIP(), []int{0}
}

func (x *SendExcelRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *SendExcelRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *SendExcelRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendExcelRequest) GetFilename() string {
	if x != nil && x.Filename != nil {
		return *x.Filename
	}
	return ""
}

func (x *SendExcelRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SendExcelRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// The response message containing the greetings
type SendExcelReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendExcelReply) Reset() {
	*x = SendExcelReply{}
	mi := &file_protoc_excel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendExcelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendExcelReply) ProtoMessage() {}

func (x *SendExcelReply) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_excel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendExcelReply.ProtoReflect.Descriptor instead.
func (*SendExcelReply) Descriptor() ([]byte, []int) {
	return file_protoc_excel_proto_rawDescGZIP(), []int{1}
}

func (x *SendExcelReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_protoc_excel_proto protoreflect.FileDescriptor

const file_protoc_excel_proto_rawDesc = "" +
	"\n" +
	"\x12protoc/excel.proto\x12\rat.energydash\"\xdd\x01\n" +
	"\x10SendExcelRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x1f\n" +
	"\bfilename\x18\x04 \x01(\tH\x00R\bfilename\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x05 \x01(\fH\x01R\acontent\x88\x01\x01\x12\x17\n" +
	"\x04body\x18\x06 \x01(\fH\x02R\x04body\x88\x01\x01B\v\n" +
	"\t_filenameB\n" +
	"\n" +
	"\b_contentB\a\n" +
	"\x05_body\"(\n" +
	"\x0eSendExcelReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2b\n" +
	"\x11ExcelAdminService\x12M\n" +
	"\tSendExcel\x12\x1f.at.energydash.SendExcelRequest\x1a\x1d.at.energydash.SendExcelReply\"\x00BP\n" +
	"\x19at.energydash.admin.excelB\x0fExcelAdminProtoP\x01Z at.ourproject/energystore/protocb\x06proto3"

var (
	file_protoc_excel_proto_rawDescOnce sync.Once
	file_protoc_excel_proto_rawDescData []byte
)

func file_protoc_excel_proto_rawDescGZIP() []byte {
	file_protoc_excel_proto_rawDescOnce.Do(func() {
		file_protoc_excel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoc_excel_proto_rawDesc), len(file_protoc_excel_proto_rawDesc)))
	})
	return file_protoc_excel_proto_rawDescData
}

var file_protoc_excel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protoc_excel_proto_goTypes = []any{
	(*SendExcelRequest)(nil), // 0: at.energydash.SendExcelRequest
	(*SendExcelReply)(nil),   // 1: at.energydash.SendExcelReply
}
var file_protoc_excel_proto_depIdxs = []int32{
	0, // 0: at.energydash.ExcelAdminService.SendExcel:input_type -> at.energydash.SendExcelRequest
	1, // 1: at.energydash.ExcelAdminService.SendExcel:output_type -> at.energydash.SendExcelReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoc_excel_proto_init() }
func file_protoc_excel_proto_init() {
	if File_protoc_excel_proto != nil {
		return
	}
	file_protoc_excel_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoc_excel_proto_rawDesc), len(file_protoc_excel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoc_excel_proto_goTypes,
		DependencyIndexes: file_protoc_excel_proto_depIdxs,
		MessageInfos:      file_protoc_excel_proto_msgTypes,
	}.Build()
	File_protoc_excel_proto = out.File
	file_protoc_excel_proto_goTypes = nil
	file_protoc_excel_proto_depIdxs = nil
}
