// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protoc/masterdata.proto

package protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MeteringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Status        uint32                 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	From          *uint64                `protobuf:"varint,3,opt,name=from,proto3,oneof" json:"from,omitempty"`
	To            *uint64                `protobuf:"varint,4,opt,name=to,proto3,oneof" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeteringRequest) Reset() {
	*x = MeteringRequest{}
	mi := &file_protoc_masterdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeteringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeteringRequest) ProtoMessage() {}

func (x *MeteringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_masterdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeteringRequest.ProtoReflect.Descriptor instead.
func (*MeteringRequest) Descriptor() ([]byte, []int) {
	return file_protoc_masterdata_proto_rawDescGZIP(), []int{0}
}

func (x *MeteringRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *MeteringRequest) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MeteringRequest) GetFrom() uint64 {
	if x != nil && x.From != nil {
		return *x.From
	}
	return 0
}

func (x *MeteringRequest) GetTo() uint64 {
	if x != nil && x.To != nil {
		return *x.To
	}
	return 0
}

// The response message containing the greetings
type MeteringPointReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	MeteringPoints []*MeteringPoint       `protobuf:"bytes,2,rep,name=meteringPoints,proto3" json:"meteringPoints,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MeteringPointReply) Reset() {
	*x = MeteringPointReply{}
	mi := &file_protoc_masterdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeteringPointReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeteringPointReply) ProtoMessage() {}

func (x *MeteringPointReply) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_masterdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeteringPointReply.ProtoReflect.Descriptor instead.
func (*MeteringPointReply) Descriptor() ([]byte, []int) {
	return file_protoc_masterdata_proto_rawDescGZIP(), []int{1}
}

func (x *MeteringPointReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MeteringPointReply) GetMeteringPoints() []*MeteringPoint {
	if x != nil {
		return x.MeteringPoints
	}
	return nil
}

type MeteringPoint struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MeteringPointId string                 `protobuf:"bytes,1,opt,name=meteringPointId,proto3" json:"meteringPointId,omitempty"`
	Direction       string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	PartFact        uint32                 `protobuf:"varint,4,opt,name=partFact,proto3" json:"partFact,omitempty"`
	ActiveSince     *uint64                `protobuf:"varint,5,opt,name=activeSince,proto3,oneof" json:"activeSince,omitempty"`
	InactiveSince   *uint64                `protobuf:"varint,6,opt,name=inactiveSince,proto3,oneof" json:"inactiveSince,omitempty"`
	Transformer     *string                `protobuf:"bytes,7,opt,name=transformer,proto3,oneof" json:"transformer,omitempty"`
	EquipmentNumber *string                `protobuf:"bytes,8,opt,name=equipmentNumber,proto3,oneof" json:"equipmentNumber,omitempty"`
	EquipmentName   *string                `protobuf:"bytes,9,opt,name=equipmentName,proto3,oneof" json:"equipmentName,omitempty"`
	InverterId      *string                `protobuf:"bytes,10,opt,name=inverterId,proto3,oneof" json:"inverterId,omitempty"`
	Street          *string                `protobuf:"bytes,11,opt,name=street,proto3,oneof" json:"street,omitempty"`
	StreetNumber    *string                `protobuf:"bytes,12,opt,name=streetNumber,proto3,oneof" json:"streetNumber,omitempty"`
	City            *string                `protobuf:"bytes,13,opt,name=city,proto3,oneof" json:"city,omitempty"`
	Zip             *string                `protobuf:"bytes,14,opt,name=zip,proto3,oneof" json:"zip,omitempty"`
	RegisteredSince *uint64                `protobuf:"varint,15,opt,name=registeredSince,proto3,oneof" json:"registeredSince,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MeteringPoint) Reset() {
	*x = MeteringPoint{}
	mi := &file_protoc_masterdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeteringPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeteringPoint) ProtoMessage() {}

func (x *MeteringPoint) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_masterdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeteringPoint.ProtoReflect.Descriptor instead.
func (*MeteringPoint) Descriptor() ([]byte, []int) {
	return file_protoc_masterdata_proto_rawDescGZIP(), []int{2}
}

func (x *MeteringPoint) GetMeteringPointId() string {
	if x != nil {
		return x.MeteringPointId
	}
	return ""
}

func (x *MeteringPoint) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *MeteringPoint) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MeteringPoint) GetPartFact() uint32 {
	if x != nil {
		return x.PartFact
	}
	return 0
}

func (x *MeteringPoint) GetActiveSince() uint64 {
	if x != nil && x.ActiveSince != nil {
		return *x.ActiveSince
	}
	return 0
}

func (x *MeteringPoint) GetInactiveSince() uint64 {
	if x != nil && x.InactiveSince != nil {
		return *x.InactiveSince
	}
	return 0
}

func (x *MeteringPoint) GetTransformer() string {
	if x != nil && x.Transformer != nil {
		return *x.Transformer
	}
	return ""
}

func (x *MeteringPoint) GetEquipmentNumber() string {
	if x != nil && x.EquipmentNumber != nil {
		return *x.EquipmentNumber
	}
	return ""
}

func (x *MeteringPoint) GetEquipmentName() string {
	if x != nil && x.EquipmentName != nil {
		return *x.EquipmentName
	}
	return ""
}

func (x *MeteringPoint) GetInverterId() string {
	if x != nil && x.InverterId != nil {
		return *x.InverterId
	}
	return ""
}

func (x *MeteringPoint) GetStreet() string {
	if x != nil && x.Street != nil {
		return *x.Street
	}
	return ""
}

func (x *MeteringPoint) GetStreetNumber() string {
	if x != nil && x.StreetNumber != nil {
		return *x.StreetNumber
	}
	return ""
}

func (x *MeteringPoint) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *MeteringPoint) GetZip() string {
	if x != nil && x.Zip != nil {
		return *x.Zip
	}
	return ""
}

func (x *MeteringPoint) GetRegisteredSince() uint64 {
	if x != nil && x.RegisteredSince != nil {
		return *x.RegisteredSince
	}
	return 0
}

var File_protoc_masterdata_proto protoreflect.FileDescriptor

const file_protoc_masterdata_proto_rawDesc = "" +
	"\n" +
	"\x17protoc/masterdata.proto\x12\rat.energydash\"\x7f\n" +
	"\x0fMeteringRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x16\n" +
	"\x06status\x18\x02 \x01(\rR\x06status\x12\x17\n" +
	"\x04from\x18\x03 \x01(\x04H\x00R\x04from\x88\x01\x01\x12\x13\n" +
	"\x02to\x18\x04 \x01(\x04H\x01R\x02to\x88\x01\x01B\a\n" +
	"\x05_fromB\x05\n" +
	"\x03_to\"r\n" +
	"\x12MeteringPointReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12D\n" +
	"\x0emeteringPoints\x18\x02 \x03(\v2\x1c.at.energydash.MeteringPointR\x0emeteringPoints\"\xd0\x05\n" +
	"\rMeteringPoint\x12(\n" +
	"\x0fmeteringPointId\x18\x01 \x01(\tR\x0fmeteringPointId\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bpartFact\x18\x04 \x01(\rR\bpartFact\x12%\n" +
	"\vactiveSince\x18\x05 \x01(\x04H\x00R\vactiveSince\x88\x01\x01\x12)\n" +
	"\rinactiveSince\x18\x06 \x01(\x04H\x01R\rinactiveSince\x88\x01\x01\x12%\n" +
	"\vtransformer\x18\a \x01(\tH\x02R\vtransformer\x88\x01\x01\x12-\n" +
	"\x0fequipmentNumber\x18\b \x01(\tH\x03R\x0fequipmentNumber\x88\x01\x01\x12)\n" +
	"\requipmentName\x18\t \x01(\tH\x04R\requipmentName\x88\x01\x01\x12#\n" +
	"\n" +
	"inverterId\x18\n" +
	" \x01(\tH\x05R\n" +
	"inverterId\x88\x01\x01\x12\x1b\n" +
	"\x06street\x18\v \x01(\tH\x06R\x06street\x88\x01\x01\x12'\n" +
	"\fstreetNumber\x18\f \x01(\tH\aR\fstreetNumber\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\r \x01(\tH\bR\x04city\x88\x01\x01\x12\x15\n" +
	"\x03zip\x18\x0e \x01(\tH\tR\x03zip\x88\x01\x01\x12-\n" +
	"\x0fregisteredSince\x18\x0f \x01(\x04H\n" +
	"R\x0fregisteredSince\x88\x01\x01B\x0e\n" +
	"\f_activeSinceB\x10\n" +
	"\x0e_inactiveSinceB\x0e\n" +
	"\f_transformerB\x12\n" +
	"\x10_equipmentNumberB\x10\n" +
	"\x0e_equipmentNameB\r\n" +
	"\v_inverterIdB\t\n" +
	"\a_streetB\x0f\n" +
	"\r_streetNumberB\a\n" +
	"\x05_cityB\x06\n" +
	"\x04_zipB\x12\n" +
	"\x10_registeredSince2m\n" +
	"\n" +
	"ApiService\x12_\n" +
	"\x18MasterData_MeteringPoint\x12\x1e.at.energydash.MeteringRequest\x1a!.at.energydash.MeteringPointReply\"\x00BU\n" +
	"\x1eat.energydash.admin.masterdataB\x0fMasterdataProtoP\x01Z at.ourproject/energystore/protocb\x06proto3"

var (
	file_protoc_masterdata_proto_rawDescOnce sync.Once
	file_protoc_masterdata_proto_rawDescData []byte
)

func file_protoc_masterdata_proto_rawDescGZIP() []byte {
	file_protoc_masterdata_proto_rawDescOnce.Do(func() {
		file_protoc_masterdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoc_masterdata_proto_rawDesc), len(file_protoc_masterdata_proto_rawDesc)))
	})
	return file_protoc_masterdata_proto_rawDescData
}

var file_protoc_masterdata_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protoc_masterdata_proto_goTypes = []any{
	(*MeteringRequest)(nil),    // 0: at.energydash.MeteringRequest
	(*MeteringPointReply)(nil), // 1: at.energydash.MeteringPointReply
	(*MeteringPoint)(nil),      // 2: at.energydash.MeteringPoint
}
var file_protoc_masterdata_proto_depIdxs = []int32{
	2, // 0: at.energydash.MeteringPointReply.meteringPoints:type_name -> at.energydash.MeteringPoint
	0, // 1: at.energydash.ApiService.MasterData_MeteringPoint:input_type -> at.energydash.MeteringRequest
	1, // 2: at.energydash.ApiService.MasterData_MeteringPoint:output_type -> at.energydash.MeteringPointReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protoc_masterdata_proto_init() }
func file_protoc_masterdata_proto_init() {
	if File_protoc_masterdata_proto != nil {
		return
	}
	file_protoc_masterdata_proto_msgTypes[0].OneofWrappers = []any{}
	file_protoc_masterdata_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoc_masterdata_proto_rawDesc), len(file_protoc_masterdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoc_masterdata_proto_goTypes,
		DependencyIndexes: file_protoc_masterdata_proto_depIdxs,
		MessageInfos:      file_protoc_masterdata_proto_msgTypes,
	}.Build()
	File_protoc_masterdata_proto = out.File
	file_protoc_masterdata_proto_goTypes = nil
	file_protoc_masterdata_proto_depIdxs = nil
}
