
persistence:
  path: "../../rawdata"

jwt:
  privKeyFile: "./zertifikat-key.pem"
  pubKeyFile: "./zertifikat-pub.pem"

mqtt:
  host: "localhost:1883"
  id: "edash-energystore-1"
  qos: 1
  energySubscriptionTopic: "eda/response/energy/+"

services:
  mail-server: "localhost:9090"
